In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
 
print("a =", a)
print("a.ndim  =", a.ndim)   # dimensijų skaičius
print("a.shape =", a.shape)  # forma
print("a.size  =", a.size)   # elementų kiekis
print("a.dtype =", a.dtype)  # duomenų tipas

In [ ]:
# 2D masyvas (dvi dimensijos, dažnai vadinamas matrica)
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print("b =\n", b)
print("b.ndim  =", b.ndim)
print("b.shape =", b.shape)  # 2 eilutės, 3 stulpeliai
print("b.size  =", b.size)   # 2 * 3 = 6 elementai
print("b.dtype =", b.dtype)
 

In [ ]:
x = np.array([5, 10, 15])
y = np.array([[1, 2], [3, 4]])
 
print("x =", x)
print("y =\n", y)

In [ ]:
#np.ones

ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3
 
print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)

In [ ]:
#zeros and ones

zeros_1d = np.zeros(4)
zeros_2d = np.zeros((3, 2))
 
print("zeros_1d =", zeros_1d)
print("zeros_2d =\n", zeros_2d)


In [ ]:
#np.arange

seq1 = np.arange(0, 10)        # 0, 1, 2, ..., 9
seq2 = np.arange(2, 11, 2)     # 2, 4, 6, 8, 10
 
print("seq1 =", seq1)
print("seq2 =", seq2)
 

In [ ]:
in1 = np.linspace(0, 1, 5)      # 5 reikšmės nuo 0 iki 1
lin2 = np.linspace(10, 20, 3)    # 10, 15, 20
 
print("lin1 =", lin1)
print("lin2 =", lin2)

In [ ]:
# reshape:formos keitimas

# Pradinis 1D masyvas su 6 elementais
r = np.arange(1, 7)   # [1, 2, 3, 4, 5, 6]
 
print("r =", r)
print("r.shape =", r.shape)

In [ ]:
#Formos pakeitimas į 2x3
r_2x3 = r.reshape(2, 3)
 
print("r_2x3 =\n", r_2x3)
print("r_2x3.shape =", r_2x3.shape)

In [ ]:
#pirmas elementas turi imdeksa 0
#antars elementas turi indeksa 1
#rArray indexing

a = np.array([10, 20, 30, 40, 50])
 
print("a =", a)
print("a[0]  =", a[0])   # pirmas elementas
print("a[2]  =", a[2])   # trečias elementas
print("a[-1] =", a[-1])  # paskutinis elementas

In [ ]:
#2D masyvo indeksavo


np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])
 
print("b =\n", b)
print("b[0, 0] =", b[0, 0])   # 1 (pirma eilutė, pirmas stulpelis)
print("b[1, 2] =", b[1, 2])   # 6 (antra eilutė, trečias stulpelis)
print("b[-1, -1] =", b[-1, -1])  # 9 (paskutinė eilutė, paskutinis stulpelis)

In [ ]:
#2. Indexing and slicing (rezimas )
#slicing sintakce: start:stop:step

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
print("x =", x)
print("x[2:6] =", x[2:6])      # elementai su indeksais 2,3,4,5
print("x[:4]  =", x[:4])       # nuo pradžios iki 4 (neįtraukiant)
print("x[5:]  =", x[5:])       # nuo 5 iki galo
print("x[::2] =", x[::2])      # kas antras elementas
print("x[::-1] =", x[::-1])    # apsukimas atgaline tvarka


In [ ]:
#slicing in 2D masyve 
#reziai gali buti taikome ir eilutems ir stulpeliams b[eiluciu_rezis, stulpeliu_rezis]


In [ ]:
#Array operation
#Numpy leidzia atlikti operacijas elementu lygiu sudetis atimtis 

p = np.array([1, 2, 3, 4])
q = np.array([10, 20, 30, 40])
 
print("p =", p)
print("q =", q)
 
print("p + q =", p + q)     # elementų suma
print("q - p =", q - p)     # elementų skirtumas
print("p * 2 =", p * 2)     # daugyba iš skaičiaus
print("q / 10 =", q / 10)   # dalyba iš skaičiaus (rezultatas dažnai tampa float)

In [ ]:
#lyginimo operacija, rezultatas yra boolean tipo masyvas (true, false)

values = np.array([3, 7, 2, 9, 5])
 
print("values =", values)
print("values > 5 =", values > 5)
print("values == 7 =", values == 7)

In [ ]:
#Filtrtering arrays , filtravimas dazniausiai daroma su boolean  kauke

values = np.array([3, 7, 2, 9, 5])
 
mask = values > 5
filtered = values[mask]
 
print("values =", values)
print("mask =", mask)
print("values[mask] =", filtered)

In [ ]:
#naudojant and & ir | or 

values = np.array([3, 7, 2, 9, 5, 8, 1])
 
mask_between = (values >= 3) & (values <= 8)
print("values =", values)
print("mask_between =", mask_between)
print("values[mask_between] =", values[mask_between])

In [ ]:
#modifying array values ( reiksmiu keitimas), reiksmiu keitimas)

m = np.array([10, 20, 30, 40, 50])
print("Pradinis m =", m)
 
m[1] = 999  # pakeičiama viena reikšmė pagal indeksą
print("Po m[1] = 999:", m)
 
m[m > 40] = 0  # pakeičiamos visos reikšmės, kurios tenkina sąlygą
print("Po m[m >= 40] = 0:", m)
 

In [ ]:
#np.where function (logical test,value if True, value if False) sis metodas patogus
# kai reikia sukurti masyva pagal taisykles.

scores = np.array([40, 55, 70, 90, 30])
 
result = np.where(scores >= 60, "Pass", "Fail")
 
print("scores =", scores)
print("result =", result)


In [ ]:
#naudojams ir duomenu perrasymui 

values = np.array([5, -2, 7, -1, 0])
 
# Neigiamas reikšmes pakeičia į 0, o kitas palieka kaip yra
non_negative = np.where(values < 0, 0, values)
 
print("values =", values)
print("non_negative =", non_negative)
 

In [ ]:
#array aggregation method ( agregavimo metodai) grazina viena skaiciu apibendrinanty masyva

data = np.array([2, 4, 6, 8, 10])
 
print("data =", data)
print("sum  =", data.sum())
print("mean =", data.mean())
print("min  =", data.min())
print("max  =", data.max())
print("std  =", data.std())

In [ ]:
# aggregavimas  2D masyve pagal eilutes (axis =1) pagal stulpelius (axis=0)

mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
print("mat =\n", mat)
print("Suma pagal stulpelius (axis=0):", mat.sum(axis=0))  # [1+4, 2+5, 3+6]
print("Suma pagal eilutes (axis=1):", mat.sum(axis=1))    # [1+2+3, 4+5+6]
 
 

In [ ]:
#array daznos funkcijos : 

arr = np.array([3, 1, 2, 3, 2, 2, 5])
 
print("arr =", arr)
print("unique =", np.unique(arr))
print("sorted =", np.sort(arr))

In [ ]:
vals = np.array([-5, 0, 3, 10, 15])
 
# Apriboja reikšmes intervale [0, 10]
clipped = np.clip(vals, 0, 10)
 
print("vals =", vals)
print("clipped =", clipped)

In [ ]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5])
 
combined = np.concatenate([a1, a2])
 
print("a1 =", a1)
print("a2 =", a2)
print("combined =", combined)

In [ ]:
#Vectorized operation -reiskia kad vietoj for ciklo  atliekama operacija su visu masyvu vienu veiksmu
# Broadcasting - reiskia kad Numpy leidzia atlikti operacijas tarp masyvu skirtingui formu 

mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
add_row = np.array([10, 20, 30])  # forma (3,)
 
# Vektorius pridedamas prie kiekvienos eilutės (eilutė po eilutės)
result = mat + add_row
 
print("mat =\n", mat)
print("add_row =", add_row)
print("mat + add_row =\n", result)
 

In [ ]:
# operacijos su matricomis -m skiriamos dvi svarbios operaciju grupes 
# elemento lygio ir matricu sandauga 

A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A =\n", A)
print("B =\n", B)
 
# Elementų lygio sudėtis ir daugyba
print("A + B =\n", A + B)
print("A * B (element-wise) =\n", A * B)



In [ ]:
#matricu sandauga su @

A = np.array([
    [1, 2],
    [3, 4]
])
 
B = np.array([
    [10, 20],
    [30, 40]
])
 
print("A @ B =\n", A @ B)

In [ ]:
# matrica ir skaliaras (skaicius)

M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M * 10 =\n", M * 10)
print("M + 1 =\n", M + 1)

In [ ]:
#matricos transportavimas- sukeicia eilutes ir stulpelius , tam naudojama T

M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])
 
print("M =\n", M)
print("M.T =\n", M.T)
print("M.shape =", M.shape)
print("M.T.shape =", M.T.shape)

In [ ]:
#elementu ise funkcija 

pos = np.array([1, 4, 9, 16])
 
print("pos =", pos)
print("sqrt =", np.sqrt(pos))
print("log =", np.log(pos))
print("exp =", np.exp(np.array([0, 1, 2])))


In [ ]:
#metodai: matematinaiai ir statistiniai 
#sum,mean, min, max
 import numpy as np

data = np.array([5, 2, 9, 1, 7])
 
print("data =", data)
print("sum =", data.sum())
print("mean =", data.mean())
print("min =", data.min())
print("max =", data.max())
print("median =", np.median(data))
print("std =", data.std())
print("var =", data.var())


In [8]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
 
print("mat =\n", mat)
print("Vidurkis pagal stulpelius (axis=0):", mat.mean(axis=0))
print("Vidurkis pagal eilutes (axis=1):", mat.mean(axis=1))

mat =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vidurkis pagal stulpelius (axis=0): [4. 5. 6.]
Vidurkis pagal eilutes (axis=1): [2. 5. 8.]


In [ ]:
#boolean indeksasvimas ir skaiciavimas vienoje frazeje   

prices = np.array([9.99, 14.50, 3.20, 25.00, 7.80])
 
mask = prices > 10
high_prices = prices[mask]
 
print("prices =", prices)
print("mask =", mask)
print("high_prices =", high_prices)
print("high_prices count =", mask.sum())
print("high_prices mean =", high_prices.mean())

In [ ]:
scores = np.array([40, 55, 70, 90, 30])
 
passed = scores >= 60
 
print("scores =", scores)
print("passed =", passed)
 
print("any passed =", passed.any())
print("all passed =", passed.all())
print("passed count =", passed.sum())

In [ ]:
# rashape pakeicia masyvo forma, nekeiciant elemento kiekio

# Formos pakeitimas į 3x4

a_3x4 = a.reshape(3, 4)
print("a_3x4 =\n", a_3x4)
print("a_3x4.shape =", a_3x4.shape)

In [ ]:
# Automatinis vienos dimensijos parinkimas su -1
a_auto = a.reshape(2, -1)   # 2 eilutės, stulpelių skaičius apskaičiuojamas automatiškai
print("a_auto =\n", a_auto)
print("a_auto.shape =", a_auto.shape)

In [ ]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
 
flat = m.flatten()
rav = m.ravel()
 
print("m =\n", m)
print("flatten() =", flat)
print("ravel()   =", rav)